# Generated by Django 4.2.28 on 2026-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_seiled',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
