# Generated by Django 4.2.28 on 2026-03-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_product_quantity_in_stock_product_quantity_seiled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100000),
        ),
    ]
