# Generated by Django 4.2.28 on 2026-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0003_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_annuler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECEIPT'), ('I', 'INVOICE'), ('P', 'PROFORMA INVOICE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_update_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
