# Generated by Django 4.2.28 on 2026-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0004_invoice_is_annuler_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_update_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
